"""initial schema

Revision ID: 5f05c451e48b
Revises: 
Create Date: 2026-01-08 00:57:11.572239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f05c451e48b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flat_number', sa.String(length=20), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('building_section', sa.String(length=50), nullable=False),
    sa.Column('area_sqft', sa.Integer(), nullable=False),
    sa.Column('ownership_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flats_flat_number'), 'flats', ['flat_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('RESIDENT', 'SECURITY', 'ASSOCIATION_STAFF', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('monthly_fees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flat_id', sa.UUID(), nullable=False),
    sa.Column('month_year', sa.String(length=10), nullable=False),
    sa.Column('base_amount', sa.Integer(), nullable=False),
    sa.Column('maintenance_charge', sa.Integer(), nullable=True),
    sa.Column('water_charge', sa.Integer(), nullable=True),
    sa.Column('other_charges', sa.Integer(), nullable=True),
    sa.Column('penalty_amount', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_fees_flat_id'), 'monthly_fees', ['flat_id'], unique=False)
    op.create_index(op.f('ix_monthly_fees_status'), 'monthly_fees', ['status'], unique=False)
    op.create_table('notices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('published_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='noticestatus'), nullable=True),
    sa.Column('published_date', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notice_published_by', 'notices', ['published_by_id'], unique=False)
    op.create_index('idx_notice_status', 'notices', ['status'], unique=False)
    op.create_index(op.f('ix_notices_status'), 'notices', ['status'], unique=False)
    op.create_table('residents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('flat_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'INACTIVE', name='residentstatus'), nullable=True),
    sa.Column('move_in_date', sa.String(length=50), nullable=True),
    sa.Column('id_proof_url', sa.String(length=255), nullable=True),
    sa.Column('ownership_proof_url', sa.String(length=255), nullable=True),
    sa.Column('family_members', sa.Integer(), nullable=True),
    sa.Column('vehicle_details', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resident_status', 'residents', ['status'], unique=False)
    op.create_index('idx_resident_user_flat', 'residents', ['user_id', 'flat_id'], unique=False)
    op.create_index(op.f('ix_residents_flat_id'), 'residents', ['flat_id'], unique=False)
    op.create_index(op.f('ix_residents_status'), 'residents', ['status'], unique=False)
    op.create_index(op.f('ix_residents_user_id'), 'residents', ['user_id'], unique=False)
    op.create_table('visitor_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flat_id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('visitor_name', sa.String(length=255), nullable=False),
    sa.Column('visitor_phone', sa.String(length=20), nullable=False),
    sa.Column('visitor_id_proof', sa.String(length=50), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_visitor_entry_exit', 'visitor_logs', ['entry_time', 'exit_time'], unique=False)
    op.create_index('idx_visitor_flat', 'visitor_logs', ['flat_id'], unique=False)
    op.create_index(op.f('ix_visitor_logs_entry_time'), 'visitor_logs', ['entry_time'], unique=False)
    op.create_index(op.f('ix_visitor_logs_flat_id'), 'visitor_logs', ['flat_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('fee_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=True),
    sa.Column('payment_date', sa.String(length=50), nullable=False),
    sa.Column('receipt_url', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fee_id'], ['monthly_fees.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('idx_payment_resident', 'payments', ['resident_id'], unique=False)
    op.create_index('idx_payment_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payment_transaction', 'payments', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_payments_resident_id'), 'payments', ['resident_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('flat_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority'), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Integer(), nullable=True),
    sa.Column('actual_cost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ticket_assigned', 'tickets', ['assigned_to_id'], unique=False)
    op.create_index('idx_ticket_flat', 'tickets', ['flat_id'], unique=False)
    op.create_index('idx_ticket_resident', 'tickets', ['resident_id'], unique=False)
    op.create_index('idx_ticket_status', 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_flat_id'), 'tickets', ['flat_id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_resident_id'), 'tickets', ['resident_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_number'), 'tickets', ['ticket_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_ticket_number'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_resident_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_flat_id'), table_name='tickets')
    op.drop_index('idx_ticket_status', table_name='tickets')
    op.drop_index('idx_ticket_resident', table_name='tickets')
    op.drop_index('idx_ticket_flat', table_name='tickets')
    op.drop_index('idx_ticket_assigned', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_resident_id'), table_name='payments')
    op.drop_index('idx_payment_transaction', table_name='payments')
    op.drop_index('idx_payment_status', table_name='payments')
    op.drop_index('idx_payment_resident', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_visitor_logs_flat_id'), table_name='visitor_logs')
    op.drop_index(op.f('ix_visitor_logs_entry_time'), table_name='visitor_logs')
    op.drop_index('idx_visitor_flat', table_name='visitor_logs')
    op.drop_index('idx_visitor_entry_exit', table_name='visitor_logs')
    op.drop_table('visitor_logs')
    op.drop_index(op.f('ix_residents_user_id'), table_name='residents')
    op.drop_index(op.f('ix_residents_status'), table_name='residents')
    op.drop_index(op.f('ix_residents_flat_id'), table_name='residents')
    op.drop_index('idx_resident_user_flat', table_name='residents')
    op.drop_index('idx_resident_status', table_name='residents')
    op.drop_table('residents')
    op.drop_index(op.f('ix_notices_status'), table_name='notices')
    op.drop_index('idx_notice_status', table_name='notices')
    op.drop_index('idx_notice_published_by', table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_monthly_fees_status'), table_name='monthly_fees')
    op.drop_index(op.f('ix_monthly_fees_flat_id'), table_name='monthly_fees')
    op.drop_table('monthly_fees')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_flats_flat_number'), table_name='flats')
    op.drop_table('flats')
    # ### end Alembic commands ###
